info:
  version: '${project.version}'
  title: JsIncluder Plugin
  description: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://jira.mail.ru/rest/jsincluder/1.0
    description: Plugin Endpoint URL